version: '3'
services:
  # --- Infrastructure: Zookeeper ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # --- Infrastructure: Kafka ---
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # --- Application: Producer ---
  crypto-producer:
    build: .
    container_name: crypto_producer
    depends_on:
      - kafka
    command: python src/producers/btc_producer.py
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:29092'

  # --- Application: Processor (Spark) ---
  spark-processor:
    build: .
    container_name: spark_processor
    depends_on:
      - kafka
    command: python src/processors/stream_processor.py
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:29092'
      MYSQL_HOST: 'host.docker.internal'
      MYSQL_PASSWORD: ${MYSQL_REAL_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"

# --- Visualization: Grafana ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    extra_hosts:
      - "host.docker.internal:host-gateway"