version: '3'
services:
  # --- Infrastructure: Zookeeper ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - crypto-net

  # --- Infrastructure: Kafka ---
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - crypto-net

  # --- Infrastructure: MySQL (DENTRO DO DOCKER) ---
  mysql-db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crypto_project
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql_data:/var/lib/mysql
    networks:
      - crypto-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # --- Application: Producer ---
  crypto-producer:
    build: .
    container_name: crypto_producer
    depends_on:
      - kafka
    command: python src/producers/btc_producer.py
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:29092'
    networks:
      - crypto-net

  # --- Application: Processor (Spark) ---
  spark-processor:
    build: .
    container_name: spark_processor
    depends_on:
      kafka:
        condition: service_started
      mysql-db:
        condition: service_healthy
    command: python src/processors/stream_processor.py
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:29092'
      MYSQL_HOST: 'mysql-db'
      MYSQL_PORT: '3306'
      MYSQL_DB: 'crypto_project'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'rootpassword'
    networks:
      - crypto-net

  # --- Visualization: Grafana ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - crypto-net

networks:
  crypto-net:
    driver: bridge